name: NoCheat
version: ${project.version}
description: ${project.description}

author: Evenprime
website: ${project.url}

main: cc.co.evenprime.bukkit.nocheat.NoCheat


commands:
  nocheat:
    description: NoCheat command(s)
    permission: nocheat.admin.commands
    usage: |
           /<command> permlist player [permission] - to list the NoCheat relevant permissions of the player, optionally only those starting with [permission]
           /<command> reload - to reload NoCheats configuration file(s), without reloading the plugin itself
           /<command> performance - to show some performance data of NoCheat
           /<command> playerinfo playername - show the collected data NoCheat collected about a player

permissions:
  nocheat:
    description: Allow a player to bypass all checks and give him all admin permissions
    children:
      nocheat.admin:
        description: Give a player all admin rights
        children:
          nocheat.admin.chatlog:
            description: Player can see NoCheats log messages in the ingame chat
          nocheat.admin.commands:
            description: allow use of the "nocheat" commands
      nocheat.checks:
        description: Allow the player to bypass all checks
        children:
          nocheat.checks.moving: 
            description: Allow the player to bypass all moving related checks
            children:
              nocheat.checks.moving.runfly:
                description: Allow a player to move as free and as fast as he wants (ignores flying, swimming and sneaking settings)
              nocheat.checks.moving.flying:
                description: Allow a player to fly, but only within given speed limits (ignores swimming and sneaking settings)
              nocheat.checks.moving.swimming:
                description: Allow a player to move through water without slowdown
              nocheat.checks.moving.sneaking:
                description: Allow a player to sneak without slowdown
              nocheat.checks.moving.vehicle:
                description: Allow a player to speed in vehicles faster than normal
              nocheat.checks.moving.nofall:
                description: Allow a player to cheat and not take fall damage at all
              nocheat.checks.moving.morepackets:
                description: Allow a player to send more move-event-packets than normal, causing him to move faster than normal
              nocheat.checks.moving.morepacketsvehicle:
                description: Allow a player to send more vehicle-move-event-packets than normal, causing him to move faster than normal
              nocheat.checks.moving.boatonground:
                description: Allow a player to place a boat on the ground (not only on the water)
              nocheat.checks.moving.respawntrick:
                description: Allow a player to respawn on top if blocked by gravel or sand (instead of removing the blocks)
          nocheat.checks.blockbreak:
            description: Allow the player to bypass all blockbreak checks
            children:
              nocheat.checks.blockbreak.reach:
                description: Allow a player to break blocks at maximum range (about 6-7 blocks, in creative mode unlimited)
              nocheat.checks.blockbreak.direction:
                description: Allow a player to break blocks that are not in front of them
              nocheat.checks.blockbreak.noswing:
                description: Allow a player to break blocks without swinging their arm
          nocheat.checks.blockplace:
            description: Allow the player to bypass all blockplace checks
            children:
              nocheat.checks.blockplace.reach:
                description: Allow a player to place blocks at maximum range (about 6-7 blocks)
              nocheat.checks.blockplace.direction:
                description: Allow a player to place blocks outside their line of view
          nocheat.checks.chat:
            description: Allow the player to bypass all chat checks
            children:
              nocheat.checks.chat.spam:
                description: Allow a player to send an infinite amount of chat messages
              nocheat.checks.chat.color:
                description: Allow a player to send colored chat messages
              nocheat.checks.chat.empty:
                description: Allow a player to send empty messages (normally not possible)
          nocheat.checks.fight:
            description: Allow the player to bypass all fight checks
            children:
              nocheat.checks.fight.direction:
                description: Allow a player to attack players and monster even if they are not in his field of view
              nocheat.checks.fight.noswing:
                description: Allow a player to fight without swinging their arm
              nocheat.checks.fight.reach:
                description: Allow a player to fight over bigger distances than usual
              nocheat.checks.fight.speed:
                description: Allow a player to attack faster than usual
          nocheat.checks.inventory:
            description: Allow the player to bypass all inventory checks
            children:
              nocheat.checks.inventory.drop:
                description: Allow a player to drop more items in a short timeframe than the defined limit
